version: "3"

services:
  database:
    image: mongo
    ports:
      - "27017:27017"

#   carapp:
#     build: .
#     ports:
#       - "8080:8080"
#     environment:
#       - MONGO_URI=mongodb://database:27017
#       - PORT=8080
#     restart: on-failure
#     depends_on:
#       - database
#     links:
#       - "database"